# Generated by Django 4.1.7 on 2023-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divulgar", "0004_alter_pet_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("P", "Para adoção"), ("A", "Adotado")],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
